// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRMVwFL2qb3g_qqjIwptrp5cK05a00W0',
    appId: '1:70303575406:web:afd08caca182a64ae2a57f',
    messagingSenderId: '70303575406',
    projectId: 'mobile-app-741c7',
    authDomain: 'mobile-app-741c7.firebaseapp.com',
    storageBucket: 'mobile-app-741c7.firebasestorage.app',
    measurementId: 'G-HVZG27ZKEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKBAmcMlip0TPSuoKxIwSNoVEXiTrq_cg',
    appId: '1:70303575406:android:84717c2a006c26c3e2a57f',
    messagingSenderId: '70303575406',
    projectId: 'mobile-app-741c7',
    storageBucket: 'mobile-app-741c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcuj9VgeG065dbsrfCdV0nqsZzvtn54oU',
    appId: '1:70303575406:ios:60a7ec6b86c20a0ce2a57f',
    messagingSenderId: '70303575406',
    projectId: 'mobile-app-741c7',
    storageBucket: 'mobile-app-741c7.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcuj9VgeG065dbsrfCdV0nqsZzvtn54oU',
    appId: '1:70303575406:ios:60a7ec6b86c20a0ce2a57f',
    messagingSenderId: '70303575406',
    projectId: 'mobile-app-741c7',
    storageBucket: 'mobile-app-741c7.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeRMVwFL2qb3g_qqjIwptrp5cK05a00W0',
    appId: '1:70303575406:web:9f6dbfa88d2aa74be2a57f',
    messagingSenderId: '70303575406',
    projectId: 'mobile-app-741c7',
    authDomain: 'mobile-app-741c7.firebaseapp.com',
    storageBucket: 'mobile-app-741c7.firebasestorage.app',
    measurementId: 'G-JE6MLP340J',
  );
}
